meat_products = {
    'B1000'      : 'Bovine_Meat',
    'B1100'      : 'Calf_and_Young_Cattley',
    'B1110'      : 'Calf',
    'B1120'      : 'Young_Cattle',
    'B1200'      : 'Adult_Cattle',
    'B1210'      : 'Bullock',
    'B1210_1220' : 'Bullock_and_Bull',
    'B1220'      : 'Bull',
    'B1230'      : 'Cow',
    'B1240'      : 'Heifer',
    'B3100'      : 'Pigmeat',
    'B4000'      : 'Meat_Sheep_and_Goats',
    'B4100'      : 'Sheepmeat',
    'B4110'      : 'Lamb',
    'B4120'      : 'Mutton',
    'B4200'      : 'Goat_Meat',
    'B5000'      : 'Horse_Meat',
    'B7000'      : 'Poultry_Meat',
    'B7100'      : 'Chicken',
    'B7200'      : 'Duck',
    'B7300'      : 'Turkey',
    'B7490'      : 'Other_Poultry',
}
pig_codes = {
    'A3100'      : 'Live swine, domestic species',
    'A3110'      : 'Piglets, live weight of under 20 kg',
    'A3120_3133' : 'Breeding pigs',
    'A3120'      : 'Breeding sows, live weight 50 kg or over',
    'A3120K'     : 'Covered sows',
    'A3120KA'    : 'Sows covered for the first time',
    'A3120L'     : 'Sows, not covered',
    'A3120LA'    : 'Gilts not yet covered',
    'A3131'      : 'Pigs, from 20 kg to less than 50 kg',
    'A3132'      : 'Fattening pigs, live weight 50 kg or over',
    'A3132X'     : 'Fattening pigs, from 50 kg to less than 80 kg',
    'A3132Y'     : 'Fattening pigs, from 80 kg to less than 110 kg',
    'A3132Z'     : 'Fattening pigs, live weight 110 kg or over',
    'A3133'      : 'Breeding boars'
}
countries_codes = {
    'EU27_2020'    :   'European Union - 27 countries (from 2020)',
    'EU28'         :   'European Union - 28 countries (2013-2020)',
    'EU27_2007'    :   'European Union - 27 countries (2007-2013)',
    'EU25'         :   'European Union - 25 countries (2004-2006)',
    'EU15'         :   'European Union - 15 countries (1995-2004)',
    'BE'           :   'Belgium',
    'BG'           :   'Bulgaria',
    'CZ'           :   'Czechia',
    'DK'           :   'Denmark',
    'DE'           :   'Germany',
    'EE'           :   'Estonia',
    'IE'           :   'Ireland',
    'EL'           :   'Greece',
    'ES'           :   'Spain',
    'FR'           :   'France',
    'HR'           :   'Croatia',
    'IT'           :   'Italy',
    'CY'           :   'Cyprus',
    'LV'           :   'Latvia',
    'LT'           :   'Lithuania',
    'LU'           :   'Luxembourg',
    'HU'           :   'Hungary',
    'MT'           :   'Malta',
    'NL'           :   'Netherlands',
    'AT'           :   'Austria',
    'PL'           :   'Poland',
    'PT'           :   'Portugal',
    'RO'           :   'Romania',
    'SI'           :   'Slovenia',
    'SK'           :   'Slovakia',
    'FI'           :   'Finland',
    'SE'           :   'Sweden',
    'IS'           :   'Iceland',
    'CH'           :   'Switzerland',
    'UK'           :   'United Kingdom',
    'BA'           :   'Bosnia and Herzegovina',
    'ME'           :   'Montenegro',
    'MK'           :   'North Macedonia',
    'AL'           :   'Albania',
    'RS'           :   'Serbia',
    'TR'           :   'Türkiye',
    'XK'           :   'Kosovo'
}
bovine_codes = {
    'A2000'           :   'Live bovine animals',
    'A2010'           :   'Bovine animals, less than 1 year old',
    'A2010B'          :   'Bovine animals, less than 1 year old, for slaughter',
    'A2010C'          :   'Bovine animals, less than 1 year old, not for slaughter',
    'A2020'           :   'Bovine animals, 1 to less than 2 years old',
    'A2030'           :   'Bovine animals, 2 years old or over',
    'A2110C'          :   'Male calves, less than 1 year old, not for slaughter',
    'A2120'           :   'Male bovine animals, 1 to less than 2 years old',
    'A2130'           :   'Male bovine animals, 2 years old or over',
    'A2230_2330'      :   'Female bovine animals, 2 years old or over',
    'A2210C'          :   'Female calves, less than 1 year old, not for slaughter',
    'A2220'           :   'Heifers, 1 to less than 2 years old',
    'A2220B'          :   'Heifers, 1 year old, for slaughter',
    'A2220C'          :   'Heifers, 1 year old, not for slaughter',
    'A2230'           :   'Heifers, 2 years old or over',
    'A2230B'          :   'Heifers, 2 years old or over, for slaughter',
    'A2230C'          :   'Heifers, 2 years old or over, not for slaughter',
    'A2300'           :   'Cows',
    'A2300F'          :   'Dairy cows',
    'A2300G'          :   'Non dairy cows',
    'A2400'           :   'Buffaloes',
    'A2410'           :   'Breeding female buffaloes',
    'A2420'           :   'Other buffaloes'
}
poultry_hatch_item_codes = {
    'CH'       :  'Chicks hatched',
    'CP'       :  'Chicks placed',
    'EPI'      :  'Eggs placed in incubation',
    'EXP'      :  'Exports',
    'EXP_IEU'  :  'Exports intra-EU',
    'EXP_XEU'  :  'Exports extra-EU',
    'ET'       :  'Exports - Total',
    'IMP'      :  'Imports',
    'IMP_IEU'  :  'Imports intra-EU',
    'IMP_XEU'  :  'Imports extra-EU',
    'IT'       :  'Imports - Total',
    'CU'       :  'Chicks for use'
}
poultry_codes = {
    'A5130O'   : 'Chicks of laying hen breeds (laying)',
    'A5130ON'  : 'Chicks of laying hen breeds (selection)',
    'A5130P'   : 'Chicks of meat broiler breeds (fattening)',
    'A5130PN'  : 'Chicks of meat broiler breeds (selection)',
    'A5130M'   : 'Chicks of mixed meat-laying breeds',
    'A5131P'   : 'Cockerels from sexing',
    'A5211P'   : 'Chicks of duck (fattening)',
    'A5221P'   : 'Chicks of goose (fattening)',
    'A5231P'   : 'Chicks of turkey (fattening)',
    'A5241P'   : 'Chicks of Guinea fowls (fattening)'
}
milk_codes = {
    'D1110D'        :  'Raw cows milk delivered to dairies',
    'D1200DME'      :  'Raw cream delivered to dairies (in milk equivalent)',
    'D2100'         :  'Drinking milk',
    'D2200V'        :  'Cream for direct consumption',
    'D3100_X_3113'  :  'Milk and cream powders, excluding skimmed milk powders',
    'D3113'         :  'Skimmed milk powder',
    'D3200'         :  'Concentrated milk',
    'D4100'         :  'Acidified milk (yoghurts and other)',
    'D6000'         :  'Butter, incl. dehydrated butter and ghee, and other fats and oils derived from milk; dairy spreads',
    'D7121'         :  'Cheese from cows milk (pure)'
}