INDICATORS = {
    'corn_usage': {
        "CORN_BEVERAGE_ALCOHOL_BU": "CORN, FOR BEVERAGE ALCOHOL - USAGE, MEASURED IN BU",
        "CORN_FUEL_ALCOHOL_BU": "CORN, FOR FUEL ALCOHOL - USAGE, MEASURED IN BU",
        "CORN_INDUSTRIAL_ALCOHOL_BU": "CORN, FOR INDUSTRIAL ALCOHOL - USAGE, MEASURED IN BU",
        "CORN_OTHER_PRODUCTS_EXCL_ALCOHOL_BU": "CORN, FOR OTHER PRODUCTS (EXCL ALCOHOL) - USAGE, MEASURED IN BU"
    },
    'alcohol_coproducts': {
        "CO2_CAPTURED_TONS": "ALCOHOL COPRODUCTS, CARBON DIOXIDE - CAPTURED, MEASURED IN TONS",
        "CDO_PRODUCTION_TONS": "ALCOHOL COPRODUCTS, CORN DISTILLERS OIL (CDO) - PRODUCTION, MEASURED IN TONS",
        "CORN_GERM_MEAL_TONS": "ALCOHOL COPRODUCTS, CORN GERM MEAL - PRODUCTION, MEASURED IN TONS",
        "CORN_GLUTEN_FEED_MEDIUM_PROTEIN_TONS": "ALCOHOL COPRODUCTS, CORN GLUTEN FEED, MEDIUM PROTEIN, FROM BRAN & STEEP WATER - PRODUCTION, MEASURED IN TONS",
        "CORN_GLUTEN_FEED_WET_40_60_TONS": "ALCOHOL COPRODUCTS, CORN GLUTEN FEED, WET, 40 - 60 PCT MOISTURE - PRODUCTION, MEASURED IN TONS",
        "CORN_GLUTEN_MEAL_HIGH_PROTEIN_TONS": "ALCOHOL COPRODUCTS, CORN GLUTEN MEAL, HIGH PROTEIN CONCENTRATE - PRODUCTION, MEASURED IN TONS",
        "DISTILLERS_GRAINS_DRIED_EXCL_SOLUBLES_TONS": "ALCOHOL COPRODUCTS, DISTILLERS GRAINS, DRIED, (EXCL SOLUBLES) - PRODUCTION, MEASURED IN TONS",
        "DISTILLERS_GRAINS_DRIED_INCL_SOLUBLES_TONS": "ALCOHOL COPRODUCTS, DISTILLERS GRAINS, DRIED, INCL SOLUBLES - PRODUCTION, MEASURED IN TONS",
        "DISTILLERS_GRAINS_WET_40_64_TONS": "ALCOHOL COPRODUCTS, DISTILLERS GRAINS, WET, 40 - 64 PCT MOISTURE - PRODUCTION, MEASURED IN TONS",
        "DISTILLERS_GRAINS_WET_GE65_TONS": "ALCOHOL COPRODUCTS, DISTILLERS GRAINS, WET, GE 65 PCT MOISTURE - PRODUCTION, MEASURED IN TONS",
        "DISTILLERS_SOLUBLES_CONDENSED_SYRUP_TONS": "ALCOHOL COPRODUCTS, DISTILLERS SOLUBLES, CONDENSED (SYRUP) - PRODUCTION, MEASURED IN TONS"
    }
}