INDICATORS = {
    'corn' :  {
        "DENTED"             : "CORN - PROGRESS, MEASURED IN PCT DENTED",
        "DOUGH"              : "CORN - PROGRESS, MEASURED IN PCT DOUGH",
        "EMERGED"            : "CORN - PROGRESS, MEASURED IN PCT EMERGED",
        "MATURE"             : "CORN - PROGRESS, MEASURED IN PCT MATURE",
        "MILK"               : "CORN - PROGRESS, MEASURED IN PCT MILK",
        "PLANTED"            : "CORN - PROGRESS, MEASURED IN PCT PLANTED",
        "SILKING"            : "CORN - PROGRESS, MEASURED IN PCT SILKING",
        "HARVESTED"          : "CORN, GRAIN - PROGRESS, MEASURED IN PCT HARVESTED"
    },
    "spring_wheat_excl_durum": {
        "BOOTED"    : "WHEAT, SPRING, (EXCL DURUM) - PROGRESS, MEASURED IN PCT BOOTED",
        "COLORING"  : "WHEAT, SPRING, (EXCL DURUM) - PROGRESS, MEASURED IN PCT COLORING",
        "EMERGED"   : "WHEAT, SPRING, (EXCL DURUM) - PROGRESS, MEASURED IN PCT EMERGED",
        "HARVESTED" : "WHEAT, SPRING, (EXCL DURUM) - PROGRESS, MEASURED IN PCT HARVESTED",
        "HEADED"    : "WHEAT, SPRING, (EXCL DURUM) - PROGRESS, MEASURED IN PCT HEADED",
        "JOINTING"  : "WHEAT, SPRING, (EXCL DURUM) - PROGRESS, MEASURED IN PCT JOINTING",
        "MATURE"    : "WHEAT, SPRING, (EXCL DURUM) - PROGRESS, MEASURED IN PCT MATURE",
        "PLANTED"   : "WHEAT, SPRING, (EXCL DURUM) - PROGRESS, MEASURED IN PCT PLANTED"
    },
    "spring_wheat_durum": {
        "BOOTED"    : "WHEAT, SPRING, DURUM - PROGRESS, MEASURED IN PCT BOOTED",
        "COLORING"  : "WHEAT, SPRING, DURUM - PROGRESS, MEASURED IN PCT COLORING",
        "EMERGED"   : "WHEAT, SPRING, DURUM - PROGRESS, MEASURED IN PCT EMERGED",
        "HARVESTED" : "WHEAT, SPRING, DURUM - PROGRESS, MEASURED IN PCT HARVESTED",
        "HEADED"    : "WHEAT, SPRING, DURUM - PROGRESS, MEASURED IN PCT HEADED",
        "JOINTING"  : "WHEAT, SPRING, DURUM - PROGRESS, MEASURED IN PCT JOINTING",
        "MATURE"    : "WHEAT, SPRING, DURUM - PROGRESS, MEASURED IN PCT MATURE",
        "PLANTED"   : "WHEAT, SPRING, DURUM - PROGRESS, MEASURED IN PCT PLANTED"
    },
    "winter_wheat": {
        "BOOTED"            : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT BOOTED",
        "BREAKING_DORMANCY" : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT BREAKING DORMANCY",
        "COLORING"          : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT COLORING",
        "EMERGED"           : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT EMERGED",
        "HARVESTED"         : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT HARVESTED",
        "HEADED"            : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT HEADED",
        "JOINTING"          : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT JOINTING",
        "MATURE"            : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT MATURE",
        "PASTURED"          : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT PASTURED",
        "PLANTED"           : "WHEAT, WINTER - PROGRESS, MEASURED IN PCT PLANTED",
    },
    "soybeans": {
        "BLOOMING"         : "SOYBEANS - PROGRESS, MEASURED IN PCT BLOOMING",
        "COLORING"         : "SOYBEANS - PROGRESS, MEASURED IN PCT COLORING",
        "DROPPING_LEAVES"  : "SOYBEANS - PROGRESS, MEASURED IN PCT DROPPING LEAVES",
        "EMERGED"          : "SOYBEANS - PROGRESS, MEASURED IN PCT EMERGED",
        "FULLY_PODDED"     : "SOYBEANS - PROGRESS, MEASURED IN PCT FULLY PODDED",
        "HARVESTED"        : "SOYBEANS - PROGRESS, MEASURED IN PCT HARVESTED",
        "MATURE"           : "SOYBEANS - PROGRESS, MEASURED IN PCT MATURE",
        "PLANTED"          : "SOYBEANS - PROGRESS, MEASURED IN PCT PLANTED",
        "SETTING_PODS" : "SOYBEANS - PROGRESS, MEASURED IN PCT SETTING PODS",
    }

    }