INDICATORS = {
    'corn_ear_count': {
        "CORN_EAR_COUNT_ACRE": "CORN, GRAIN - EAR COUNT, MEASURED IN EARS / ACRE",
        "CORN_EAR_COUNT_IRRIGATED_ACRE": "CORN, GRAIN, IRRIGATED - EAR COUNT, MEASURED IN EARS / ACRE",
        "CORN_EAR_COUNT_NON_IRRIGATED_ACRE": "CORN, GRAIN, NON-IRRIGATED - EAR COUNT, MEASURED IN EARS / ACRE"
    },
    'soybeans_pod_count': {
        "SOYBEANS_POD_COUNT_18SQFT": "SOYBEANS - POD COUNT, MEASURED IN PODS / 18 SQ FT"
    }
}