INDICATORS = {
    'corn' :  {
        "CORN_POPULATION"                       : "CORN, GRAIN - PLANT POPULATION, MEASURED IN PLANTS / ACRE",
        "CORN_IRRIGATED_POPULATION"             : "CORN, GRAIN, IRRIGATED - PLANT POPULATION, MEASURED IN PLANTS / ACRE",
        "CORN_NON_IRRIGATED_POPULATION"         : "CORN, GRAIN, NON-IRRIGATED - PLANT POPULATION, MEASURED IN PLANTS / ACRE",
    },
    'soybean' : {
        "SOYBEAN_POPULATION"                    : "SOYBEANS - POD COUNT, MEASURED IN PODS / 18 SQ FT"
    }
    }